#!/bin/bash

set -e

ROOT_FOLDER=build/bin
VERSION=0.38.1
KTLINT_BIN=$ROOT_FOLDER/ktlint-$VERSION
SCAN_DIR="app/src/main/java/com/ub/finanstics"

mkdir -p $ROOT_FOLDER

if [ ! -f "$KTLINT_BIN" ]; then
  echo "Please wait, first download..."
  rm -f $ROOT_FOLDER/ktlint-*
  curl -sSL https://github.com/pinterest/ktlint/releases/download/$VERSION/ktlint --output $KTLINT_BIN
  chmod a+x $KTLINT_BIN
fi

if [ $CI ]; then
  export REVIEWDOG_GITHUB_API_TOKEN="${GITHUB_TOKEN}"
  $KTLINT_BIN --android --disabled_rules=indent,parameter-list-wrapping,import-ordering --reporter=checkstyle --editorconfig=/.editorconfig "$SCAN_DIR" |
    reviewdog -f=checkstyle \
      -name="ktlint" \
      -reporter="github-pr-review" \
      -fail-level=error
else
  $KTLINT_BIN --android --disabled_rules=indent,parameter-list-wrapping --editorconfig=/.editorconfig "$SCAN_DIR" "$@"
fi

echo "Done!"
